### ISSUE TITLE
Installing the Viewer, and doing a `qlmanage -r` doesn't seem to make it work

### ISSUE THREAD

**Issue by jjarava** [digitalmoksha/QLCommonMark#1]
Hi!

Love the CommonMark idea, and am trying to get the viewer to work.

I've got the release, unzipped it, put the file in `~/Library/QuickLook`, done a `qlmanage -r` and `sudo qlmanage -r` and it doesn't seem to work... (attaching screenshot)

![image](https://cloud.githubusercontent.com/assets/2682444/25184188/05cf1548-251a-11e7-9c6e-cccbd5b70256.png)

I'm running OSX 10.11:

```bash
2017-04-19 16:06:09 jjarava testing $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1421
```

And the plugin seems to be properly registered for quite a few "file types".

```bash
2017-04-19 16:07:03 jjarava testing $ qlmanage -m plugins | grep CommonMark
  net.multimarkdown.text -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
  com.foldingtext.foldingtext.document -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
  dyn.ah62d4rv4ge80445e -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
  com.unknown.md -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
  net.daringfireball.markdown -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
  net.daringfireball -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
  dyn.ah62d4rv4ge8042pwrrwg875s -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
  org.vim.markdown-file -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
  dyn.ah62d4rv4ge8045pe -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
  dyn.ah62d4rv4ge8043a -> /Users/jjarava/Library/QuickLook/QLCommonMark.qlgenerator (1)
```

So, what might be the issue here?

Thanks!

**Comment by jjarava** [comment]
HI!

I seem to have sorted it out.

Testing with `mdls` was telling me that the "File type" was `net.ia.markdown`:

```
2017-04-19 16:30:21 jjarava testing $ mdls Readme.md

<snipped for clarity>

kMDItemContentType             = "net.ia.markdown"
kMDItemContentTypeTree         = (
    "net.ia.markdown",
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```

Running `qlmanage -d1 -p Readme.md` I got the details on what QL Plugin the system was opening it with (some lines deleted for clarity): 

```bash
2017-04-19 16:29:28 jjarava testing $ qlmanage -d1 -p Readme.md
Testing Quick Look preview with files:
	Readme.md
[DEBUG] Preview test for Readme.md -- file:///Users/jjarava/Downloads/QuickLook%20Plugins/testing/. Content type UTI: net.ia.markdown
[DEBUG] Previewing file:///Users/jjarava/Downloads/QuickLook%20Plugins/testing/Readme.md. Content type UTI: net.ia.markdown. Generator used: <QLGenerator Text.qlgenerator>
[DEBUG] Loading <QLGenerator Text.qlgenerator>
[DEBUG] Previewing file:///Users/jjarava/Downloads/QuickLook%20Plugins/testing/Readme.md finished
```

Googling around, found quite a lot of "pain" around unwanted/lingering UTI associations. I arrived at:

https://www.cocoanetics.com/2012/09/fun-with-uti/
and 
https://superuser.com/questions/263311/on-os-x-how-do-you-change-a-files-kind

and the TL;DR answer is - [resetting the Launch Services Registry](https://apple.stackexchange.com/a/68600/21650) (same thing that's used to fix "Open With"), seemed to fix it:

`/System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -kill -r -domain local -domain system -domain user`

So hope this helps!

(as you can see below, the QL Preview is **much** nicer now! - thanks for creating this QL extension!)

![image](https://cloud.githubusercontent.com/assets/2682444/25187045/4474508a-2522-11e7-8545-601aa17dcea0.png)

**Comment by digitalmoksha** [comment]
@jjarava glad you got it working.  It can be a bit a tricky with QuickLook plugins.  Thank you for posting the steps you went through to get it working.  When I have some time, I might add a troubleshooting section to the readme.
