### ISSUE TITLE
Custom CSS style for preview

### ISSUE THREAD

**Issue by htr3n** [digitalmoksha/QLCommonMark#3]
Hi, 
many thanks for your nice QL plugin that supports CommonMark. It looks very promising. Btw, is there any way to customize the preview using CSS style just like MMD QuickLook Plugin does?

Cheers,
Huy

**Comment by digitalmoksha** [comment]
@htr3n thank you, glad you like it.

Yes, you can completely override the built in styles by creating the css file `~/.cmqlstyle.css`.  The MMD version uses `~/.mdqlstyle.css`

**Comment by digitalmoksha** [comment]
Note to self: document `~/.cmqlstyle.css` in the README

**Comment by htr3n** [comment]
Thank you very much. I will close the issue then :)
