### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by alexwhittemore** [digitalmoksha/QLCommonMark#4]
Not so much an issue, feel free to close as soon as you feel appropriately praised. I just wanted to say thank you so much for taking the time to make this! I've been looking for a QL plugin for Markdown that supports all the same modern features like Github and Wordpress, and this is the first one I've come across that renders my documentation to my satisfaction! Huzzah for properly-rendered mixed lists :)

**Comment by digitalmoksha** [comment]
Hey @alexwhittemore , thanks for the shoutout - I appreciate it!  Glad you find it useful...
